package population.vcf.utils;

import java.util.ArrayList;
import java.util.List;

public class SVVcfUtils {
	
	
	
	/**
	 * retrieve the list of integer values from the 'CIPOS', 'CIEND', 'CIPOS95', 'CIEND95' attributes from VCF file generated by delly and lumpy
	 * 
	 * 		CIPOS=-10,119;CIPOS95=0,29
	 * @param value
	 * @return
	 */
	public static List<Integer> getCIPOSCIENDAttributeValues(Object value){
		String stringValue=value.toString().trim();
//		System.out.println(stringValue);
		
		stringValue=stringValue.substring(1, stringValue.length()-1);
		
		String[] splits=stringValue.split(",");
		
		List<Integer> ret=new ArrayList<>();
		
		for(String split:splits) {
			ret.add(Integer.parseInt(split.trim()));
		}
		return ret;
	}
}
